### ISSUE TITLE
Crash report for mod in 1.12.2 (without optifine)

### ISSUE THREAD

**Issue by RyTEM05** [necauqua/chiseled-me#25]
Recently the mod has not worked in version 1.12.2, I use it with the chisel and bits mod (Which is also 1.12.2) 
The game starts as usual, for about 10 seconds at least. and then this error message pops up
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/minecraftforge/common/IRarity
I tried using other versions on 1.12.2 and it would say the same error again.
The mod used to work around February last year, but now all the time it comes up with that crash message
Also yes i removed optifine
if you can fix this thank you so much!

**Comment by LorenzoPapi** [comment]
Have you tried the latest version of forge 1.12.2? And can you say
which forge version/s you used?

**Comment by RyTEM05** [comment]
Yes I have used the latest version and here are the versions I used to see if it worked:
1.12.2-forge1.12.2-14.23.5.2838 (latest)
1.12.2-forge1.12.2-14.23.2.2611
1.12.2-forge1.12.2-14.23.5.2768
1.12.2-forge1.12.2-14.23.5.2810
I hope this somehow helps!

**Comment by LorenzoPapi** [comment]
Latest version isn't forge 1.12.2-forge1.12.2-14.23.5.2838;
it's 1.12.2-forge1.12.2-14.23.5.2847

**Comment by LorenzoPapi** [comment]
Try it

**Comment by RyTEM05** [comment]
i just tried using the latest one and it came up with a different error message 
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer

**Comment by RyTEM05** [comment]
wait nvm i used a previous version of the mod i just used the latest version and now it works! Thank you so much!

**Comment by necauqua** [comment]
Yep, that first issue was because of old Forge version
Will be fixed anyway in the next version.
